### ISSUE TITLE
GitHub dark mode makes some logos unreadable

### ISSUE THREAD

**Issue by dar5hak** [hirenchauhan2/hirenchauhan2#1]
Specifically, Angular, Babel and express are barely visible against the new dark background.

![image](https://user-images.githubusercontent.com/8205055/102607201-e2e6dd00-414d-11eb-9882-02012fad92be.png)

**Comment by hirenchauhan2** [comment]
Thanks for catching that @dar5hak! 
Currently, there's no way to check for dark mode in MD, so I'll have to look for an alternate way. Let me know if you have any suggestions.

**Comment by dar5hak** [comment]
For Angular and Babel, you could just use the red and yellow coloured logos. For Express, check out the favicon on http://expressjs.com.

**Comment by hirenchauhan2** [comment]
Switched to https://shields.io for badges instead of logo images.
